import "./globals.css";
import styles from "@/app/styles/w3.css"
import { Mulish } from "next/font/google";
import Header from "@/app/components/Header";
import NavMenu from "@/app/components/NavMenu";

const mulish = Mulish({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
  display: 'swap' 
});

export const metadata = {
  title: "ALGO APP",
  description: "Generated by Algo Trader",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="{mulish.className}">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
      </head>
      <body className="w3-light-grey">
        <Header />
        <NavMenu />
        {children}
        </body>
    </html>
  );
}
